apiVersion: v1
kind: Service
metadata:
  name: service-helloworldv2
spec:
  selector:
    app: app-helloworldv2
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
#      nodePort: 30012